name: Replace Values in YAML and JSON Files
description: |
  This action replaces values in YAML and JSON files using environment variables.

inputs:
  target:
    description: 'The directory or file to scan for YAML and JSON files.'
    required: false
    default: 'k8s'

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /envrep

branding:
  icon: 'refresh-cw'
  color: 'green'
